server:
  port: 5000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/gateway/user/**
        filters:
        - StripPrefix=1
  # 链路追踪配置
  zipkin:
    base-url: http://localhost:9411
  # 调用采样率
  sleuth:
    sampler:
      probability: 1.0
  # RabbitMQ配置
  rabbitmq:
    host: 192.168.31.124
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka