server:
  port: 8762
spring:
  application:
    name: user-service
  # 链路追踪配置
  zipkin:
    base-url: http://localhost:9411
  # 调用采样率
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
